#!/bin/bash

#Get command line tools and Ruby
xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#Get Node
brew update
brew install node

#Get MedImage
sudo npm install pm2@latest -g
pm2 delete medimage-server
sudo npm install medimage -g
sudo chown -R $USER:$(id -gn $USER) /Users/$(id -un)/.config
mkdir ~/medimage
mkdir ~/medimage/photos
sleep 2
cd "$(npm prefix -global)/lib/node_modules/medimage/"
cp addons/configORIGINAL.json addons/config.json
sudo chown $(id -un) addons/config.json
sudo cp macconfig.json ~/medimage/config.json
pm2 start npm --name "medimage-server" -- start ./medimage-server.sh; cd ~
pm2 set medimage:configFile ~/medimage
pm2 save
pm2 startup | pbcopy
awk 'f {print; exit} /following command:/ {f=1}' <<< $(pbpaste)
echo
echo "Starting MedImage Server in browser..."
sleep 2
/Applications/Safari.app/Contents/MacOS/Safari & sleep 1 && osascript -e 'tell application "Safari" to open location "http://localhost:5566/pages/addon-settings.html"' > /dev/null 2>&1
