#!/bin/bash

#Get command line tools and Ruby
xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#Get Node
brew update
brew install node

#Get MedImage
sudo npm install pm2@latest -g
pm2 delete medimage-server
sudo npm install medimage -g
sudo chown -R $USER:$(id -gn $USER) /Users/apple/.config
mkdir ~/medimage
cd "$(npm prefix -global)/lib/node_modules/medimage/"
sudo cp addons/configORIGINAL.json addons/config.json
sudo cp macconfig.json ~/medimage/config.json
pm2 start npm --name "medimage-server" -- start ./medimage-server.sh; cd ~
pm2 save
pm2 startup 
echo "(MedImage Server: copy and run the 'sudo env...' line above, to get autostart at boot-up)"
/Applications/Safari.app/Contents/MacOS/Safari & sleep 1 && osascript -e 'tell application "Safari" to open location "http://localhost:5566/pages/addon-settings.html"'
