#!/bin/bash
sudo npm install pm2@latest -g
sudo npm install medimage -g
sudo chown -R $USER:$(id -gn $USER) /Users/apple/.config
cd "$(npm prefix -global)/lib/node_modules/medimage/"
mkdir ~/medimage
cp newconfig.json ~/medimage/config.json
npm config set medimage:configFile ~/medimage/config.json
pm2 start npm --name "medimage-server" -- start ./medimage-server.sh; cd ~
pm2 save
pm2 startup 
echo "(MedImage Server: copy and run the line above, to get autostart at boot-up)"
